version: '3.8'

services:
  ordering:
    build:
      context: ./ordering
    ports:
      - "${ORDERING_PORT:-3001}:3001"
    restart: always
    env_file:
      - ./ordering/.env
      - ./ordering/backend/.env

  admin:
    build:
      context: ./admin
    ports:
      - "${ADMIN_PORT:-3002}:80"
    restart: always
    env_file:
      - ./admin/.env
